name: Android CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Create properties file with empty API key
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY || 'a' }}
        run: echo MAPS_API_KEY="${MAPS_API_KEY}" >> local.properties
      - name: Build with Gradle
        #run: ./gradlew build
        run: ./gradlew buildDebug
      - name: Run Unit Tests
        run: ./gradlew testDebug

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis_playstore
          arch: x86
          profile: Nexus 6
          script: >
            adb logcat -c && adb logcat -f /sdcard/logcat.txt &
            ./gradlew connectedDebugAndroidTest --stacktrace ||
            ( adb pull /sdcard/logcat.txt build/reports/; exit 1 )
            #./gradlew connectedCheck --stacktrace ||

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: app/build/reports
        if: failure()
