name: Android CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Create properties file with empty API key
      run: echo MAPS_API_KEY=a >> local.properties
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis_playstore
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace

    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: app/build/reports
      if: failure()
